version: '3'
services:

  app:
    build: .docker/php-fpm
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge